<?php
/*------------------------------------------------------------------------
 # VT Products - Version 1.0
 * Copyright (C) 2013 The 7up Theme. All Rights Reserved.
 * Author: 7up Theme
 * Websites: http://www.7uptheme.com
-------------------------------------------------------------------------*/

$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$uniqued = rand().time();
$_enabletime=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection_time/isenabled_time_deal');
if($_enabletime=="1"){
	 $_productsrc=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection/product_source');
	 $_productids=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection/product_ids');
	 $_productcate=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection/product_category');
	 $_productstart=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection_time/limitation_time_start');
	 $_productfinish=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection_time/limitation_time_finish');
	 $_producthour=Mage::getStoreConfig('vt_productsconfig_cfg/product_selection_time/limitation_time_hour_finish');

 $datenow=date_create(date("m/d/Y"));
$datest=date_create($_productstart);
$datefn=date_create($_productfinish);
$totaldate=date_diff($datest,$datefn);
$diffnow=date_diff($datest,$datenow);
if($diffnow->format("%R%a")>=0){
	if($diffnow=date_diff($datenow,$datefn)>=0){
		$diffrm=date_diff($datenow,$datefn);
		$diffrm->format("%R%a");
		if($diffrm>=0){
			//echo '</br>';
			$hnow=date("h");
			$mnow=date("i");
			$snow=date("s");
			$hfn=23-$hnow;
			$mfn=59-$mnow;
			$sfn=60-$snow;	
			$src=$this->product_source_time;
			$imgWidth = $this->product_image_width;
			$imgHeight = $this->product_image_height;

			if ($imgWidth <= 0 || $imgHeight <= 0){
				$this->product_image_disp = false;
			}
			if($_productsrc=="catalog"){
				$category = new Mage_Catalog_Model_Category();
				$category->load($_productcate);
				$_productCollection = $category->getProductCollection();
				$_productCollection->addAttributeToSelect('*');		
			}
			else{//product id;
				$_productids=explode(",",$_productids);
			}
			?>
			<?php 
				$flag=true;
				if($_productsrc=="catalog" && !$_productCollection->count()) $flag=false;
				if($_productsrc=="product" && count($_productids)<=0) $flag=false;
				if(!$flag):
			?>
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			<?php else: ?>
			<div id="vt_slider<?php echo $uniqued; ?>" class="block vt-slider">
				<div class="slider-inner">
					<?php if($this->title!="") : ?>
					<div class="block-title-slider">
						<?php if($this->title!="") : ?>
							<h3 class="g-font"><?php echo $this->title;?></h3>
						<?php endif; ?>
						<?php if($this->pretext!="") : ?>
							<p class="pretext g-font"><?php echo $this->pretext;?></p>
						<?php endif; ?>		
					</div>
					<div class="line-background"><span></span></div>
					<?php endif; ?>
					<div class="container-slider">
						<div class="products-grid">
						<?php if($_productsrc=="catalog") foreach($_productCollection as $_product):  ?>
						<?php
							$now = date("Y-m-d H:m:s");
							$newsFrom= $_product->getNewsFromDate();
							$newsTo=  $_product->getNewsToDate();
							$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
							$special_from_date = $_product->getSpecialFromDate();
							$special_to_date = $_product->getSpecialToDate(); 
							$datestsp=date_create($special_from_date);
							$datefnsp=date_create($special_to_date);
							
							if(date_diff($datenow,$datefnsp)->format("%R")!="-" && date_diff($datenow,$datestsp)->format("%R")!="+" && $specialprice >0 && date_diff($datefnsp,$datefn)->format("%R")=="-"):
							?>
							<div class="item">
								
								<?php   
									if($newsFrom != ''){                            
									if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
										<div class='new-item'><?php echo $this->__("new"); ?></div>
									<?php }
									}else{
									if(($newsTo != "") && $newsTo >= $now){ 
									?>
										<div class='new-item'><?php echo $this->__("new"); ?></div>
									<?php }
									}?>
									<?php 
									if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
										<div class='sale-item'>
											<span><?php
											$saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
											<?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
										</div>
								 <?php } ?>  
								<div class="item-wrap">
									<div class="item-image">   
										<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
										<img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
										</a>
										
									</div>   
									<div class="info-product">
										<div class="pro-info">
											<div class="pro-inner">
											   <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
											   <div class="pro-content">                                                       
													<?php //echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
													<div class="wrap-price"> 
													<?php echo $this->getPriceHtml($_product, true) ?> 
													</div>
											   </div>
											</div>                                                                        
										</div>
										<div class="item-btn">
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
											   <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
											<?php endif; ?>
											<?php if($_product->isSaleable()): ?>
												<a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php //echo $this->__('Add to Cart') ?></a>
											<?php else: ?>
												<a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
											<?php endif; ?>
										   <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
											<?php endif; ?>
											
										</div>
									</div>
								</div><!--end item wrap -->
							</div>
						<?php endif;
						endforeach; 
						else
							foreach($_productids as $productid):
								$_product=Mage::getModel('catalog/product')->load($productid);
								if($_product->getName()!=""):
								?>
								<?php
									$now = date("Y-m-d H:m:s");
									$newsFrom= $_product->getNewsFromDate();
									$newsTo=  $_product->getNewsToDate();
									$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
									$special_from_date = $_product->getSpecialFromDate();
									$special_to_date = $_product->getSpecialToDate(); 
									$datestsp=date_create($special_from_date);
									$datefnsp=date_create($special_to_date);
									//echo $productid.":";
									//echo date_diff($datenow,$datefnsp)->format("%R")."+".date_diff($datenow,$datestsp)->format("%R")." ";
									if(date_diff($datenow,$datefnsp)->format("%R")!="-" && date_diff($datenow,$datestsp)->format("%R")!="+" && $specialprice >0 && date_diff($datefnsp,$datefn)->format("%R")=="-"):
								?>
								<div class="item">								
								<?php   
									if($newsFrom != ''){                            
									if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
										<div class='new-item'><?php echo $this->__("new"); ?></div>
									<?php }
									}else{
									if(($newsTo != "") && $newsTo >= $now){ 
									?>
										<div class='new-item'><?php echo $this->__("new"); ?></div>
									<?php }
									}?>
									<?php 
									if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
										<div class='sale-item'>
											<span><?php
											$saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
											<?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
										</div>
								 <?php } ?>  
								<div class="item-wrap">
									<div class="item-image">   
										<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
										<img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
										</a>
										
									</div>   
									<div class="info-product">
										<div class="pro-info">
											<div class="pro-inner">
											   <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
											   <div class="pro-content">                                                       
													<?php //echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
													<div class="wrap-price"> 
													<?php echo $this->getPriceHtml($_product, true) ?> 
													</div>
											   </div>
											</div>                                                                        
										</div>
										<div class="item-btn">
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
											   <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
											<?php endif; ?>
											<?php if($_product->isSaleable()): ?>
												<a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php //echo $this->__('Add to Cart') ?></a>
											<?php else: ?>
												<a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
											<?php endif; ?>
										   <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
											<?php endif; ?>
											
										</div>
									</div>
								</div><!--end item wrap -->
							</div>
							<?php endif; ?>
							<?php endif; endforeach;?>
						</div>
						<div class="box-nav">
							<a class="prev" href="#">Prev</a>
							<a class="next" href="#">Next</a>
						</div>
					</div>
				</div>
				<div class="pos-timer">
					<div class="timer-count-down">
						<div class="bordermid2 box-day">
							<div class="bordermid1">
								<div class="bordermid0">
									<div class="border-canvas">
										<div class="info-canvas">
											<span id="day" class="text-cd"></span>
											<div class="line-mid"></div>
											<span class="text-cd text">Days</span>
										</div>
										<canvas id="myCanvasday" width="70" height="70"></canvas>
									</div>
								</div>
							</div>
						</div>
						<div class="bordermid2 box-hour">
							<div class="bordermid1">
								<div class="bordermid0">
									<div class="border-canvas">
										<div class="info-canvas">
											<span id="hour" class="text-cd"></span>
											<div class="line-mid"></div>
											<span class="text-cd text">Hours</span>
										</div>
										<canvas id="myCanvashour" width="70" height="70"></canvas>
									</div>
								</div>
							</div>
						</div>
						<div class="bordermid2 box-minute">
							<div class="bordermid1">
								<div class="bordermid0">
									<div class="border-canvas">
										<div class="info-canvas">								
											<span id="minute" class="text-cd"></span>
											<div class="line-mid"></div>
											<span class="text-cd text">Minutes</span>
										</div>
										<canvas id="myCanvasminute" width="70" height="70"></canvas>
									</div>
								</div>
							</div>
						</div>
						<div class="bordermid2 box-second">
							<div class="bordermid1">
								<div class="bordermid0">
								<div class="border-canvas">
									<div class="info-canvas">
										<span id="second" class="text-cd"></span>
										<div class="line-mid"></div>
										<span class="text-cd text">Seconds</span>
									</div>
									<canvas id="myCanvassecond" width="70" height="70"></canvas>
								</div>
								</div>
							</div>
						</div>		
					</div>
			  </div>
			</div>  
			<script type="text/javascript">
			//<![CDATA[	
				var flycart_associated_products = <?php echo $this->getFlycartAssociatedProduct(); ?>;         
			//]]>
			</script>
			<script type="text/javascript">
			//<![CDATA[
			var totalday=<?php echo $totaldate->format("%a"); ?>, d=<?php echo $diffrm->format("%a"); ?> , h=<?php echo $hfn ?>, m=<?php echo $mfn ?>, s=<?php echo $sfn ?>;
			//var totalday=10, d=0 , h=0, m=0, s=1;
			function timedown(){
			if(d==0 && h==0 && m==0 && s==-1) {cleartime();return;}
			if(d==0 && h==0 && m==0 && s==0) {cleartime(); return;}
				s-=1;
				if(s==-1){
					var cs = document.getElementById("myCanvassecond");
					var ctxs = cs.getContext("2d");
					ctxs.clearRect(0, 0, cs.width, cs.height);
					if(m==0){
						var cm = document.getElementById("myCanvasminute");
						var ctxm = cm.getContext("2d");
						ctxm.clearRect(0, 0, cm.width, cm.height);
						if(h==0){
							var ch = document.getElementById("myCanvashour");
							var ctxh = ch.getContext("2d");
							ctxh.clearRect(0, 0, ch.width, ch.height);
							if(d!=0) {d-=1;h=59;m=59;s=59;
								if(d==0){
									var cd = document.getElementById("myCanvasday");
									var ctxd = cd.getContext("2d");
									ctxd.clearRect(0, 0, cd.width, cd.height);
								}
							}
							else {cleartime(); return;}
						}
						else{ //if h!=0
							h-=1;m=59;s=59;
						}
					}
					else{ //if m!=0
						m-=1;s=59;
					}
				}
				jQuery('#day').text(d);
				jQuery('#hour').text(h);
				jQuery('#minute').text(m);
				jQuery('#second').text(s);
				//jQuery('#canvas').text(((6*s)*Math.PI)/180);
				if(d==0 && h==0 && m==0 && s==-1) {
					cleartime();return;
				}
				if(s!=-1){
					var cs = document.getElementById("myCanvassecond");
					var ctxs = cs.getContext("2d");
					ctxs.beginPath();
					ctxs.arc(35,35,34,-Math.PI/2,((270-6*s)*Math.PI)/180);
					ctxs.lineWidth = 2; 
					ctxs.strokeStyle = "#666"; 
					ctxs.stroke();
				}
				if(m!=0){
					var cm = document.getElementById("myCanvasminute");
					var ctxm = cm.getContext("2d");
					ctxm.beginPath();
					ctxm.arc(35,35,34,-Math.PI/2,((270-6*m)*Math.PI)/180);
					ctxm.lineWidth = 2; 
					ctxm.strokeStyle = "#666"; 
					ctxm.stroke();
				}
				if(h!=0){
					var ch = document.getElementById("myCanvashour");
					var ctxh = ch.getContext("2d");
					ctxh.beginPath();
					ctxh.arc(35,35,34,-Math.PI/2,((270-(15*h))*Math.PI)/180);
					ctxh.lineWidth = 2; 
					ctxh.strokeStyle = "#666"; 
					ctxh.stroke();
				}
				if(d!=0){
					var cd = document.getElementById("myCanvasday");
					var ctxd = cd.getContext("2d");
					ctxd.beginPath();
					ctxd.arc(35,35,34,-Math.PI/2,((270-((360/totalday)*d))*Math.PI)/180);
					ctxd.lineWidth = 2; 
					ctxd.strokeStyle = "#666"; 
					ctxd.stroke();
				}
			}
			function cleartime(){	
				jQuery('.vt-slider').remove();	
				var ti=setInterval(function(){timedown()},1000);
				clearInterval(ti);
						
			}
			function clear(){
				jQuery('.vt-slider').remove();	
			}
				jQuery(document).ready(function($) {
					if(d==0 && h==0 && m==0 && s==0){clear()}
					else{
						var ti=setInterval(function(){timedown()},1000);
						$('#vt_slider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
							items: 4,
							itemsCustom: [ 
								[0, 1], 
								[480, 1], 
								[770, 2], 
								[992, 3], 
								[1200, 3] 
							],
							pagination: false,
							slideSpeed : 800,
							addClassActive: true,
							scrollPerPage: true,
							afterAction: function (e) {
								if(this.$owlItems.length > this.options.items){
									$('#vt_slider<?php echo $uniqued; ?> .box-nav').show();
								}else{
									$('#vt_slider<?php echo $uniqued; ?> .box-nav').hide();
								}
							}
							//scrollPerPage: true,
						});
					}
					$('#vt_slider<?php echo $uniqued; ?> .box-nav .prev').on('click', function(e){
						e.preventDefault();
						$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
					});
					$('#vt_slider<?php echo $uniqued; ?> .box-nav .next').on('click', function(e){
						e.preventDefault();
						$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
					});
				});
			//]]>
			</script>
			<?php endif;
		}
	}
}
}
?>
