<?php
/*------------------------------------------------------------------------
 # VT Products - Version 1.0
 * Copyright (C) 2013 The VT Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: VT Theme
 * Websites: http://www.vttheme.com
-------------------------------------------------------------------------*/
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$uniqued = rand().time();
$src=$this->product_source_time;


$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
$d=1;
$h=1;
$m=1;
$s=10;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}

?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="vt_slider<?php echo $uniqued; ?>" class="block vt-slider">
	<div class="slider-inner">
    	<div class="block-title-slider">
    		<?php if($this->title!="") : ?>
    			<h3 class="g-font"><?php echo $this->title;?></h3>
			<?php endif; ?>
    		<?php if($this->pretext!="") : ?>
    			<p class="pretext"><?php echo $this->pretext;?></p>
			<?php endif; ?>					
    	</div>
	    <div class="container-slider">
		    <div class="products-grid">
		    <?php foreach($_productCollection as $_product) : ?>
		        <?php
		        $now = date("Y-m-d H:m:s");
		        $newsFrom= $_product->getNewsFromDate();
		        $newsTo=  $_product->getNewsToDate();
		        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
		        $special_from_date = $_product->getSpecialFromDate();
		        $special_to_date = $_product->getSpecialToDate();    
		        ?>
		        <div class="item">
		        	<?php   
		                if($newsFrom != ''){                            
		                if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }else{
		                if(($newsTo != "") && $newsTo >= $now){ 
		                ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }?>
		                <?php 
		                if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
		                    <div class='sale-item'>
		                        <span><?php
		                        $saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
		                        <?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
		                    </div>
		             <?php } ?>  
					<div class="item-wrap">
                    <div class="item-image">   
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                        </a>
                        <div class="item-btn">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                               <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>
                            <?php if($_product->isSaleable()): ?>
                                <a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></a>
                            <?php else: ?>
                                <a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
                            <?php endif; ?>
                           <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                            
                        </div>  
                    </div>   
                       
                    <div class="pro-info">
                        <div class="pro-inner">
                           <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
                           <div class="pro-content">                                                       
                                <?php //echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
                                <div class="wrap-price"> 
                                <?php echo $this->getPriceHtml($_product, true) ?> 
                                </div>
                           </div>
                        </div>                                                                        
                    </div>
                    
                </div><!--end item wrap -->
		        </div>
		    <?php endforeach; ?>
		    </div>
		</div>
		<div class="box-nav">
			<a class="prev" href="#">Prev</a>
			<a class="next" href="#">Next</a>
		</div>
	</div>
	<!--div class="timer-count-down">
	<span id="day"></span>
	<span id="hour"></span>
	<span id="minute"></span>
	<span id="second"></span>
	<span id="canvas"></span>
  </div>
  <canvas id="myCanvas" width="1000" height="1000" style="border:1px solid #d3d3d3;"-->
</div>
<script type="text/javascript">
//<![CDATA[	
    var flycart_associated_products = <?php echo $this->getFlycartAssociatedProduct(); ?>;         
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#vt_slider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
        	items: 4,
            itemsCustom: [ 
            	[0, <?php echo $this->screen_phone; ?>], 
            	[480, <?php echo $this->screen_xs; ?>], 
            	[768, <?php echo $this->screen_sm; ?>], 
            	[992, <?php echo $this->screen_md; ?>], 
            	[1200, <?php echo $this->screen_lg; ?>] 
            ],
            pagination: false,
            slideSpeed : 800,
            addClassActive: true,
            scrollPerPage: true,
			afterAction: function (e) {
			    if(this.$owlItems.length > this.options.items){
			        $('#vt_slider<?php echo $uniqued; ?> .box-nav').show();
			    }else{
			        $('#vt_slider<?php echo $uniqued; ?> .box-nav').hide();
			    }
			}
            //scrollPerPage: true,
        });
		$('#vt_slider<?php echo $uniqued; ?> .box-nav .prev').on('click', function(e){
			e.preventDefault();
			$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
		});
		$('#vt_slider<?php echo $uniqued; ?> .box-nav .next').on('click', function(e){
			e.preventDefault();
			$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
		});
    });
//]]>
</script>
<?php endif; ?>
<!--script>
	//<![CDATA[	
	var d=<?php echo $d ?>, h=<?php echo $h ?>, m=<?php echo $m ?>, s=<?php echo $s ?>;
	//var d=1, h=0, m=0, s=10;
	//jQuery(document).ready(function() {		
	//	f1s();
	//	});
	function f1s(){
		
	}
	//var ti=setInterval(function(){timedown()},1000);
	function timedown(){
	
	if(d==0 && h==0 && m==0 && s==0) cleartime();
		s-=1;
		if(s==0){
			var c = document.getElementById("myCanvas");
			var ctx = c.getContext("2d");
			ctx.clearRect(0, 0, c.width, c.height);
			if(m==0){
				if(h==0){
					if(d!=0) {d-=1;h=59;m=59;s=59;}
					else {cleartime(); return;}
				}
				else{ //if h!=0
					h-=1;m=59;s=59;
				}
			}
			else{ //if m!=0
				m-=1;s=59;
			}
		}
		jQuery('#day').text(d);
		jQuery('#hour').text(h);
		jQuery('#minute').text(m);
		jQuery('#second').text(s);
		jQuery('#canvas').text(((6*s)*Math.PI)/180);
		if(d==0 && h==0 && m==0 && s==0) {
			cleartime();
		}
		if(s!=0){
		var c = document.getElementById("myCanvas");
		var ctx = c.getContext("2d");
		ctx.beginPath();
		ctx.arc(300,300,150,-Math.PI/2,((270-6*s)*Math.PI)/180);
		ctx.stroke();
		}
		//else
		//ctx.clearRect(0, 0, canvas.width, canvas.height);
		//alert(1);
		//setInterval(timedown(d,h,m,s),1000);
		//return timedown(d,h,m,s);
	}
	function cleartime(){
		
		clearInterval(ti);			
			$('.timer-count-down').empty();
			$('.timer-count-down').append('<p>Da het thoi gian</p>');
		}
		//]]>
</script-->