
<ol>

<?php foreach ($this->getItems() as $_item): ?>
    <li  <?php if(strtolower(trim($this->getName()))=='color') echo "class='color-li'"; ?>>
        <?php if ($_item->getCount() > 0): ?>
		<?php if(strtolower(trim($this->getName()))=='color'){ ?>
			<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
				<div class="color-before" style="background-color:<?php if(strtolower($_item->getLabel())=='blue') echo '#5a88ca'; else if(strtolower($_item->getLabel())=='black') echo '#000'; else if(strtolower($_item->getLabel())=='red') echo '#f93b1f'; else if(strtolower($_item->getLabel())=='brown') echo '#c08d4e'; else echo strtolower($_item->getLabel()); ?>"></div>
			</a>
		<?php } ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
        	<?php echo $_item->getLabel() ?>
        </a>		
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
        <span>(<?php echo $_item->getCount() ?>)</span>
        <?php endif; ?>
		
    </li>
<?php endforeach ?>
</ol>
