<?php
/*------------------------------------------------------------------------
 # VT RevolutionSlider - Version 1.0
 * Copyright (C) 2013 The VT Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: VT Theme
 * Websites: http://www.vtthemepro.com
-------------------------------------------------------------------------*/
$config = $this->getConfigObject();
$uq = rand().time();
$home = Mage::getSingleton('cms/page')->getIdentifier();
?>
<script type="text/javascript">
	// <![CDATA[
		jQuery(document).ready(function($) {			
		  $('#vt_slideshow<?php echo $uq ?>').revolution({
			 delay:<?php echo ($config['delay']); ?>,
			 startwidth:0,
			 startheight:<?php if($home=='home-02'){ echo "580";}else{ echo "380";}?>,
	 		 
	 		 navigationArrows:"<?php echo ($config['navigationArrows']); ?>", // nextto, solo, none

			 navigationType:"<?php echo ($config['navigationType']); ?>", // bullet, thumb, none
			 navigationStyle:"<?php echo ($config['navigationStyle']); ?>", // round,square,navbar,round-old,square-old,navbar-old

	 		<?php if(!$config['autoplay']){?>
	 		 stopAtSlide:1,
	 		 stopAfterLoops:0,
	 		<?php } ?>			 
	 
			// fullScreenOffsetContainer:".box-slideshow"
		  });
	   });
	// ]]>
</script>
	<?php if (!empty( $config['pretext'] )): ?>
		<div class="vt-pretext"><?php echo $config['pretext']; ?></div>
	<?php endif; ?>
	<?php 
	$slides = explode(',', $config['slides_html']);
	if(count($slides) > 0){
	?>
    <div class="vt-slideshow" id="vt_slideshow<?php echo $uq ?>">
		<ul>
    	<?php 
    	for($i=0;$i<count($slides);$i++) {
    		echo str_replace('</ul>', '', str_replace('<ul>', '', $this->getLayout()->createBlock('cms/block')->setBlockId(trim($slides[$i]))->toHtml()));
    	}?>
		</ul>
		<div class="tp-bannertimer<?php echo ($config['timerbar']=='bottom')?' tp-bottom':'';?>"></div>
    </div>
    <?php } ?>
    <?php if($config['posttext']): ?>
    <div class="vt-posttext"><?php echo $config['posttext'];?></div>
    <?php endif;?>