<div class="footer-col-1">
	<div class="title-col">
		<span class="g-font">Help</span>
	</div>
	<div class="content-col">
		<ul>
			<li class="first-col list-col"><a href="#"><span class="g-font">Frequently Asked Questions</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Find A Store</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Customer Services</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Delivery Information</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Arrange A Return</span></a></li>
			<li class="list-col last-col"><a href="#"><span class="g-font">Site Map</span></a></li>
		</ul>
	</div>
</div>
<div class="footer-col-2">
	<div class="title-col">
		<span class="g-font">Privacy & Legal</span>
	</div>
	<div class="content-col">
		<ul>
			<li class="list-col fist-col"><a href="#"><span class="g-font">Terms & Conditions</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">The Company</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Contact Us</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Careers & Next</span></a></li>
			<li class="list-col last-col"><a href="#"><span class="g-font">Media & Press</span></a></li>
		</ul>
	</div>
</div>
<div class="footer-col-3">
	<div class="title-col">
		<span class="g-font">Other Services</span>
	</div>
	<div class="content-col">
		<ul>
			<li class="list-col fist-col"><a href="#"><span class="g-font">Evouchers</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Giftcards</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Shoes</span></a></li>
			<li class="list-col"><a href="#"><span class="g-font">Women’s Jeans</span></a></li>
			<li class="list-col last-col"><a href="#"><span class="g-font">Maternity Clothes</span></a></li>
		</ul>
	</div>
</div>
<div class="footer-col-4">
	<div class="title-col">
		<span class="g-font">Information</span>
	</div>
	<div class="content-col">
		<ul>
			<li class="list-col fist-col"><span class="g-font home-contact">820 W. Stacy Road USA</span></li>
			<li class="list-col"><span class="g-font phone-contact">(573) 302-0171</span></li>
			<li class="list-col"><span class="g-font mail-contact">storemail@gmail.com</span></li>
			<li class="list-col last-col">
				<div class="social">
					<ul>
						<li class="fist-col-social fac"><span>facebook</span></li>
						<li class="goo"><span>google</span></li>
						<li class="twi"><span>twiter</span></li>
						<li class="last-col-social in"><span>in</span></li>						
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>